### PR TITLE
Grammar

### PR DESCRIPTION
**Pull request by Rexogamer**

### CODE REVIEW

**Review by Akanate — CHANGES_REQUESTED** [review]
I got rid of the confirm function for a reason because there are command line arguments get rid of this change of adding it back and I definitely approve. Thanks for the grammar changes though they are things you don’t pick up on.

**Comment by Rexogamer** [comment]
What did I miss?

**Comment by Akanate** [comment]
> What did I miss?

Basically I now have arguments which are used to call the function so there is no need  for the confirm anymore or admin function :)

**Comment by Rexogamer** [comment]
I removed that when I fixed the conflicts.

**Review by Akanate — APPROVED** [review]

**Pull request merged**
